packages:
  - apps/*
  - packages/*

catalog:
  "@hookform/resolvers": ^3.6.0
  "@tanstack/react-query": ^5.45.1
  "@tanstack/react-query-devtools": ^5.45.1
  "@types/js-cookie": ^3.0.6
  "@types/lodash": ^4.17.7
  "@types/luxon": ^3.4.2
  "@types/node": ^22.7.2
  axios: ^1.7.2
  jotai: ^2.9.3
  js-cookie: ^3.0.5
  lodash: ^4.17.21
  luxon: ^3.4.4
  next: 14.3.0-canary.24
  react-hook-form: ^7.51.5
  react-virtuoso: ^4.7.11
  typescript: ^5.4.5
  zod: ^3.23.8
  zustand: ^4.5.2

catalogs:
  react18:
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
    react-dom: 18.3.1
    react: 18.3.1

  graphql:
    "@types/react-relay": ^16.0.6
    "@types/relay-runtime": ^17.0.3
    "@types/relay-test-utils": ^14.1.4
    babel-plugin-relay: ^17.0.0
    get-graphql-schema: ^2.1.2
    graphql-ws: ^5.16.0
    graphql: ^16.8.1
    isomorphic-ws: ^5.0.0
    react-relay: ^16.2.0
    relay-compiler: ^16.2.0
    relay-runtime: ^16.2.0
    relay-test-utils: ^17.0.0

  tailwind:
    "@tailwindcss/typography": ^0.5.13
    autoprefixer: ^10.4.19
    postcss: ^8.4.41
    tailwindcss: ^3.4.4


  material-ui:
    "@emotion/cache": ^11.11.0
    "@emotion/react": ^11.11.4
    "@emotion/styled": ^11.11.5
    "@mui/icons-material": ^5.15.19
    "@mui/lab": ^5.0.0-alpha.170
    "@mui/material": ^5.15.19
    "@mui/material-nextjs": ^6.1.4
    "@mui/system": ^5.15.19
    "@mui/x-date-pickers": ^7.6.2

  test:
    "@cypress/webpack-dev-server": ^3.10.1
    "@testing-library/cypress": ^10.0.2
    "@testing-library/jest-dom": ^6.4.6
    "@testing-library/react": ^16.0.0
    "@testing-library/user-event": ^14.5.2
    "@types/jest": ^29.5.12
    babel-jest: ^29.7.0
    cypress-plugin-steps: ^1.1.1
    cypress: ^13.13.3
    jest-environment-jsdom: ^29.7.0
    jest: ^29.7.0
    ts-jest: ^29.1.4
    ts-node: ^10.9.2

  storybook:
    "@babel/preset-env": ^7.24.7
    "@babel/preset-react": ^7.24.7
    "@babel/preset-typescript": ^7.24.7
    "@chromatic-com/storybook": ^1.5.0
    "@storybook/addon-docs": ^8.2.8
    "@storybook/addon-essentials": ^8.2.8
    "@storybook/addon-interactions": ^8.2.8
    "@storybook/addon-links": ^8.2.8
    "@storybook/addon-styling-webpack": ^1.0.0
    "@storybook/addon-webpack5-compiler-babel": ^3.0.3
    "@storybook/blocks": ^8.2.8
    "@storybook/react": ^8.2.8
    "@storybook/react-webpack5": ^8.2.8
    "@storybook/test": ^8.2.8
    babel-loader: ^9.1.3
    css-loader: ^7.1.2
    html-webpack-plugin: ^5.6.0
    msw-storybook-addon: ^2.0.2
    msw: ^2.3.1
    postcss-loader: ^8.1.1
    storybook: ^8.2.8
    style-loader: ^4.0.0
    webpack-cli: ^5.1.4
    webpack-dev-server: ^5.0.4
    webpack: ^5.93.0

  lint:
    "@emotion/eslint-plugin": ^11.11.0
    "@next/eslint-plugin-next": ^13.1.6
    "@trivago/prettier-plugin-sort-imports": ^4.3.0
    "@types/eslint": ^9.6.1
    "@typescript-eslint/eslint-plugin": ^5.59.11
    "@typescript-eslint/parser": ^5.29.0
    eslint-config-airbnb-typescript: ^17.0.0
    eslint-config-airbnb: ^19.0.4
    eslint-config-next: ^13.4.6
    eslint-config-prettier: ^8.8.0
    eslint-plugin-import: ^2.26.0
    eslint-plugin-jsx-a11y: ^6.6.1
    eslint-plugin-react-hooks: ^4.6.0
    eslint-plugin-react: ^7.31.11
    eslint-plugin-storybook: ^0.8.0
    eslint: ^8.42.0
    husky: ^9.1.6
    lint-staged: ^14.0.1
    prettier-plugin-tailwindcss: ^0.6.3
    prettier: ^3.3.3