packages:
  - apps/*
  - packages/*

catalog:
  "@hookform/resolvers": 5.0.1
  "@tanstack/react-query": 5.76.1
  "@tanstack/react-query-devtools": 5.76.1
  "@types/js-cookie": 3.0.6
  "@types/lodash": 4.17.7
  "@types/luxon": 3.6.2
  "@types/node": 22.7.2
  "@parcel/packager-ts": ^2.14.1
  "@parcel/transformer-typescript-types": ^2.14.1
  axios: 1.9.0
  jotai: 2.12.4
  js-cookie: 3.0.5
  lodash: 4.17.21
  luxon: 3.6.1
  next: ^15.3.2
  react-international-phone: 4.5.0
  react-hook-form: 7.56.4
  react-virtuoso: 4.12.7
  simplebar-react: 3.2.5
  tsup: 8.3.6
  typescript: 5.8.3
  zod: 3.25.7
  zustand: 5.0.4
  react-multi-carousel: 2.8.6

catalogs:
  react19:
    "@types/react": 19.1.4
    "@types/react-dom": 19.1.5
    react-dom: 19.1.0
    react: 19.1.0

  react18:
    "@types/react": 18.3.3
    "@types/react-dom": 18.3.0
    react-dom: 18.3.1
    react: 18.3.1

  react-native:
    "@expo/vector-icons": ^14.0.4
    "@gorhom/bottom-sheet": ^5.1.4
    "@react-navigation/drawer": ^7.3.12
    "@react-navigation/native": ^7.1.9
    "@react-native-async-storage/async-storage": ^2.1.2
    expo-constants: ~17.1.6
    expo-file-system: ~18.1.10
    expo-image-picker: ~16.1.4
    expo-router: ~5.0.7
    expo-secure-store: ~14.2.3
    react-native-gesture-handler: ~2.24.0
    react-native-paper: ^5.14.5
    react-native-reanimated: ~3.17.4
    react-native-svg: 15.11.2
    react-native: 0.79.2

  graphql:
    "@types/react-relay": 18.2.1
    "@types/relay-runtime": 19.0.1
    "@types/relay-test-utils": 19.0.0
    babel-plugin-relay: 19.0.0
    get-graphql-schema: 2.1.2
    graphql-ws: 6.0.5
    graphql: 16.11.0
    isomorphic-ws: 5.0.0
    react-relay: 19.0.0
    relay-compiler: 19.0.0
    relay-connection-handler-plus: 0.1.2
    relay-runtime: 19.0.0
    relay-test-utils: 19.0.0

  tailwind:
    "@tailwindcss/typography": 0.5.13
    autoprefixer: 10.4.19
    postcss: 8.4.38
    tailwindcss: 3.4.4

  material-ui:
    "@emotion/cache": 11.14.0
    "@emotion/react": 11.14.0
    "@emotion/styled": 11.14.1
    "@mui/icons-material": 5.18.0
    "@mui/lab": 5.0.0-alpha.177
    "@mui/material": 5.18.0
    "@mui/material-nextjs": 6.1.4
    "@mui/system": 5.18.0
    "@mui/x-date-pickers": 7.6.2

  test:
    "@cypress/webpack-dev-server": 3.10.1
    "@faker-js/faker": ^9.0.3
    "@testing-library/cypress": 10.0.2
    "@testing-library/jest-dom": 6.4.6
    "@testing-library/react": 16.0.0
    "@testing-library/user-event": 14.5.2
    "@types/jest": 29.5.12
    babel-jest: 29.7.0
    cypress-plugin-steps: 1.1.1
    cypress-wait-until: 3.0.2
    cypress: 13.16.1
    jest-environment-jsdom: 29.7.0
    jest: 29.7.0
    ts-jest: 29.1.4
    ts-node: 10.9.2
    axios-mock-adapter: ^1.22.0

  storybook:
    "@babel/preset-env": 7.26.0
    "@babel/preset-react": 7.25.9
    "@babel/preset-typescript": 7.26.0
    "@chromatic-com/storybook": 3.2.3
    "@storybook/addon-docs": 8.4.7
    "@storybook/addon-essentials": 8.4.7
    "@storybook/addon-interactions": 8.4.7
    "@storybook/addon-links": 8.4.7
    "@storybook/addon-styling-webpack": 1.0.1
    "@storybook/addon-webpack5-compiler-babel": 3.0.3
    "@storybook/blocks": 8.4.7
    "@storybook/nextjs": 8.4.7
    "@storybook/react": 8.4.7
    "@storybook/react-webpack5": 8.4.7
    "@storybook/test": 8.4.7
    babel-loader: 9.2.1
    css-loader: 7.1.2
    html-webpack-plugin: 5.6.0
    msw-storybook-addon: 2.0.4
    msw: 2.6.6
    postcss-loader: 8.1.1
    storybook: 8.4.7
    style-loader: 4.0.0
    webpack-cli: 5.1.4
    webpack-dev-server: 5.0.4
    webpack: 5.93.0

  lint:
    "@emotion/eslint-plugin": ^11.11.0
    "@next/eslint-plugin-next": ^13.1.6
    "@trivago/prettier-plugin-sort-imports": ^4.3.0
    "@types/eslint": ^9.6.1
    "@typescript-eslint/eslint-plugin": ^5.59.11
    "@typescript-eslint/parser": ^5.29.0
    eslint-config-airbnb-typescript: ^17.0.0
    eslint-config-airbnb: ^19.0.4
    eslint-config-next: ^13.4.6
    eslint-config-prettier: ^8.8.0
    eslint-plugin-import: ^2.26.0
    eslint-plugin-jsx-a11y: ^6.6.1
    eslint-plugin-react-hooks: ^4.6.0
    eslint-plugin-react: ^7.31.11
    eslint-plugin-storybook: ^0.8.0
    eslint: ^8.42.0
    husky: ^9.1.6
    lint-staged: ^14.0.1
    prettier-plugin-tailwindcss: ^0.6.3
    prettier: ^3.3.3

  components:
    framer-motion: ^11.5.4
    numbro: ^2.5.0
    slugify: ^1.6.6
    use-long-press: ^3.2.0
    "@babel/cli": ^7.26.4
    dotenv: ^16.4.5
    dotenv-cli: ^7.4.2

  design-system:
    "@iconify/react": ^5.0.1
    "@shopify/flash-list": ^1.7.6
    color: ^4.2.3
    react-dropzone: ^14.2.3
    react-lazy-load-image-component: ^1.6.2
    "@types/color": "^4.2.0"

  eslint-plugin:
    parcel: ^2.12.0

  utils:
    events: ^3.3.0
    humps: ^2.0.1
    jwt-decode: ^4.0.0
    qs: ^6.14.0
    server-only: ^0.0.1
    "@types/humps": ^2.0.6
    "@types/qs": ^6.14.0
