name: Deploy Storybook

on:
  push:
    branches:
      - master
      - hotfix/storybook-build

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_ENV"

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: |
          rm -rf packages/components/node_modules/.cache/storybook
          pnpm --filter @baseapp-frontend/components storybook:build

      - name: Deploy Storybook to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: packages/components/storybook-static
          checkout: false
