name: Main Workflow

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-and-lint:
    name: Build and Lint Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.17.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

  test-unit:
    name: Unit Test Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Unit Test
        run: pnpm test:unit

  test-component:
    name: Component Test Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-13.16.1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Cypress binary (components workspace)
        run: |
          pnpm --filter @baseapp-frontend/components exec cypress cache path
          pnpm --filter @baseapp-frontend/components exec cypress cache list || true
          pnpm --filter @baseapp-frontend/components exec cypress install
          pnpm --filter @baseapp-frontend/components exec cypress cache list
        env:
          CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Verify Cypress binary exists
        run: |
          ls -la ~/.cache/Cypress || true
          ls -la ~/.cache/Cypress/13.16.1/Cypress || true
          test -x ~/.cache/Cypress/13.16.1/Cypress/Cypress

      - name: Component Test
        run: pnpm test:component
